# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0083_auto_20190307_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='divisionID',
        ),
    ]
