# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0085_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='groupNo',
            field=models.IntegerField(default=0),
        ),
    ]
