# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0086_title_groupno'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Division'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Title'),
        ),
    ]
