# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0088_auto_20190320_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='discord',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
