# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0092_auto_20190513_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceleveloption',
            name='optionExtraType',
        ),
        migrations.RemoveField(
            model_name='priceleveloption',
            name='optionExtraType2',
        ),
        migrations.RemoveField(
            model_name='priceleveloption',
            name='optionExtraType3',
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='optionImage',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.content_file_name),
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
