# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0093_auto_20190514_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('groupNo', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='needRoom',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='twitter',
        ),
        migrations.AddField(
            model_name='staff',
            name='accommodationType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='discord',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='roomateBlacklist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='roommateRequests',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Title'),
        ),
        migrations.AddField(
            model_name='staff',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Division'),
        ),
    ]
